server:
  port: 8080
  servlet:
    context-path: /medical-diagnosis

spring:
  datasource:
    control:
      url: jdbc:mysql://localhost:3307/control_db
      username: root
      password: root

jwt:
  signedKey: ZwEkJ3Iq7GuV4CClVnumC+TVcxzj3QaRgeeu13JkKTDA6kjv68tR6mm4gg7Ajnug
  valid-duration: 3600
  refreshable-duration: 3600
