server:
  port: 8080
  servlet:
    context-path: /medical-diagnosis
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: medsoft
    key-store-type: JKS
    key-alias: your-key-alias

spring:
  datasource:
    control:
      url: jdbc:mysql://127.0.0.1:3307/control_db
      username: root
      password: root
  jpa:
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: datndhe172134@fpt.edu.vn
    password: xqho wmni aute bmif
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

jwt:
  signedKey: ZwEkJ3Iq7GuV4CClVnumC+TVcxzj3QaRgeeu13JkKTDA6kjv68tR6mm4gg7Ajnug
  valid-duration: 3600
  refreshable-duration: 3600
