package vn.edu.fpt.medicaldiagnosis.exception;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.http.HttpStatusCode;

@Getter
@NoArgsConstructor
@AllArgsConstructor
public enum ErrorCode {

    // ===== COMMON =====
    UNCATEGORIZED(9999, "Lỗi chưa phân loại", HttpStatus.INTERNAL_SERVER_ERROR),
    INVALID_KEY(1000, "Khóa thông điệp không hợp lệ", HttpStatus.BAD_REQUEST),
    UNAUTHENTICATED(1001, "Tài khoản hoặc mật khẩu không hợp lệ", HttpStatus.UNAUTHORIZED),
    UNAUTHORIZED(1002, "Bạn không có quyền thực hiện", HttpStatus.FORBIDDEN),
    VALIDATION_ERROR(1003, "Dữ liệu không hợp lệ", HttpStatus.BAD_REQUEST),
    NO_PERMISSION(1004, "Không có quyền truy cập", HttpStatus.FORBIDDEN),
    INVALID_DATA(1005, "Dữ liệu không hợp lệ", HttpStatus.BAD_REQUEST),
    INTERNAL_SERVER_ERROR(1006, "Lỗi nội bộ máy chủ", HttpStatus.INTERNAL_SERVER_ERROR),
    ACTION_NOT_ALLOWED(1007, "Hành động không được phép", HttpStatus.FORBIDDEN),
    EMAIL_REQUIRED(1008, "Email là bắt buộc", HttpStatus.BAD_REQUEST),
    EMAIL_INVALID(1009, "Email không hợp lệ", HttpStatus.BAD_REQUEST),
    INVALID_INPUT(1010, "Dữ liệu không hợp lệ", HttpStatus.BAD_REQUEST),

    // ===== ACCOUNT =====
    ACCOUNT_EXISTED(1101, "Tài khoản đã tồn tại", HttpStatus.BAD_REQUEST),
    ACCOUNT_NOT_FOUND(1102, "Không tìm thấy tài khoản", HttpStatus.NOT_FOUND),
    ACCOUNT_USERNAME_REQUIRED(1103, "Tên đăng nhập là bắt buộc", HttpStatus.BAD_REQUEST),
    ACCOUNT_PASSWORD_INVALID(1104, "Mật khẩu phải có ít nhất 8 ký tự", HttpStatus.BAD_REQUEST),
    ACCOUNT_ROLE_REQUIRED(1105, "Vai trò là bắt buộc", HttpStatus.BAD_REQUEST),
    INVALID_NEW_PASSWORD(1106, "Mật khẩu mới không được trùng với mật khẩu cũ", HttpStatus.BAD_REQUEST),
    OLD_PASSWORD_EMPTY(1107, "Mật khẩu cũ là bắt buộc", HttpStatus.BAD_REQUEST),
    NEW_PASSWORD_EMPTY(1108, "Mật khẩu mới là bắt buộc", HttpStatus.BAD_REQUEST),
    CONFIRM_NEW_PASSWORD_EMPTY(1109, "Xác nhận mật khẩu mới là bắt buộc", HttpStatus.BAD_REQUEST),
    PASSWORD_CONFIRM_NOT_MATCH(1111, "Mật khẩu mới và mật khẩu xác nhận không khớp", HttpStatus.BAD_REQUEST),
    INVALID_OLD_PASSWORD(1112, "Mật khẩu cũ không đúng", HttpStatus.BAD_REQUEST),
    NEW_PASSWORD_INVALID(1113, "Mật khẩu mới không hợp lệ. Yêu cầu tối thiểu 8 ký tự, ít nhất 1 chữ hoa, 1 chữ số và 1 ký tự đặc biệt (@$!%*?&)", HttpStatus.BAD_REQUEST),
    CONFIRM_NEW_PASSWORD_INVALID(1114, "Mật khẩu xác nhận không hợp lệ. Phải khớp với mật khẩu mới và tuân theo quy tắc đặt mật khẩu", HttpStatus.BAD_REQUEST),

    // ===== FORGET PASSWORD =====
    FORGET_PASSWORD_USERNAME_REQUIRED(1110, "Tên đăng nhập là bắt buộc", HttpStatus.BAD_REQUEST),
    FORGET_PASSWORD_OLD_PASSWORD_REQUIRED(1111, "Mật khẩu cũ là bắt buộc", HttpStatus.BAD_REQUEST),
    FORGET_PASSWORD_OLD_PASSWORD_INVALID(1112, "Mật khẩu cũ phải có ít nhất 8 ký tự", HttpStatus.BAD_REQUEST),
    FORGET_PASSWORD_NEW_PASSWORD_REQUIRED(1113, "Mật khẩu mới là bắt buộc", HttpStatus.BAD_REQUEST),
    FORGET_PASSWORD_NEW_PASSWORD_INVALID(1114, "Mật khẩu mới phải có ít nhất 8 ký tự", HttpStatus.BAD_REQUEST),
    ACCOUNT_OR_PASSWORD_INVALID(1115, "Tài khoản hoặc mật khẩu không đúng", HttpStatus.BAD_REQUEST),

    // ===== PATIENT =====
    PATIENT_NOT_FOUND(1201, "Không tìm thấy bệnh nhân", HttpStatus.NOT_FOUND),
    PATIENT_NAME_REQUIRED(1202, "Họ và tên là bắt buộc", HttpStatus.BAD_REQUEST),
    PATIENT_CONTACT_REQUIRED(1203, "Thông tin liên hệ là bắt buộc", HttpStatus.BAD_REQUEST),
    PATIENT_DOB_REQUIRED(1205, "Ngày sinh là bắt buộc", HttpStatus.BAD_REQUEST),
    PATIENT_DOB_PAST(1206, "Ngày sinh phải ở trong quá khứ", HttpStatus.BAD_REQUEST),
    PATIENT_GENDER_REQUIRED(1207, "Giới tính là bắt buộc", HttpStatus.BAD_REQUEST),
    PATIENT_FIRST_NAME_REQUIRED(1208, "Tên là bắt buộc", HttpStatus.BAD_REQUEST),
    PATIENT_LAST_NAME_REQUIRED(1209, "Họ là bắt buộc", HttpStatus.BAD_REQUEST),
    PATIENT_PHONE_INVALID(1210, "Số điện thoại phải từ 10 đến 15 chữ số", HttpStatus.BAD_REQUEST),
    PATIENT_EMAIL_INVALID(1211, "Email không hợp lệ", HttpStatus.BAD_REQUEST),
    PATIENT_MIDDLE_NAME_REQUIRED(1212, "Tên đệm là bắt buộc", HttpStatus.BAD_REQUEST),
    PATIENT_FIRST_NAME_TOO_LONG(1213, "Tên tối đa 100 ký tự", HttpStatus.BAD_REQUEST),
    PATIENT_MIDDLE_NAME_TOO_LONG(1214, "Tên đệm tối đa 100 ký tự", HttpStatus.BAD_REQUEST),
    PATIENT_LAST_NAME_TOO_LONG(1215, "Họ tối đa 100 ký tự", HttpStatus.BAD_REQUEST),
    PATIENT_PHONE_REQUIRED(1216, "Số điện thoại là bắt buộc", HttpStatus.BAD_REQUEST),
    PATIENT_EMAIL_REQUIRED(1217, "Email là bắt buộc", HttpStatus.BAD_REQUEST),
    PATIENT_EMAIL_EXISTED(1218, "Email đã tồn tại", HttpStatus.BAD_REQUEST),
    PATIENT_PHONE_EXISTED(1219, "Số điện thoại đã tồn tại", HttpStatus.BAD_REQUEST),
    PATIENT_ID_REQUIRED(1220, "Mã bệnh nhân là bắt buộc", HttpStatus.BAD_REQUEST),

    // ===== STAFF =====
    STAFF_NAME_EMPTY(1301, "Tên nhân viên không được để trống", HttpStatus.BAD_REQUEST),
    STAFF_NAME_LENGTH(1302, "Tên nhân viên phải từ 3 đến 100 ký tự", HttpStatus.BAD_REQUEST),
    STAFF_SPECIALTY_EMPTY(1303, "Chuyên khoa không được để trống", HttpStatus.BAD_REQUEST),
    STAFF_LEVEL_EMPTY(1304, "Cấp bậc không được để trống", HttpStatus.BAD_REQUEST),
    STAFF_PHONE_EMPTY(1305, "Số điện thoại không được để trống", HttpStatus.BAD_REQUEST),
    STAFF_PHONE_INVALID(1306, "Số điện thoại phải gồm 10 chữ số", HttpStatus.BAD_REQUEST),
    STAFF_EMAIL_EMPTY(1307, "Email không được để trống", HttpStatus.BAD_REQUEST),
    STAFF_EMAIL_LENGTH(1308, "Email phải từ 3 đến 100 ký tự", HttpStatus.BAD_REQUEST),
    STAFF_EMAIL_INVALID(1309, "Email không hợp lệ", HttpStatus.BAD_REQUEST),
    STAFF_GENDER_EMPTY(1310, "Giới tính không được để trống", HttpStatus.BAD_REQUEST),
    STAFF_DOB_EMPTY(1311, "Ngày sinh không được để trống", HttpStatus.BAD_REQUEST),
    STAFF_DOB_PAST(1312, "Ngày sinh phải ở trong quá khứ", HttpStatus.BAD_REQUEST),
    STAFF_EMAIL_EXISTED(1313, "Email đã tồn tại", HttpStatus.BAD_REQUEST),
    STAFF_PHONE_EXISTED(1314, "Số điện thoại đã tồn tại", HttpStatus.BAD_REQUEST),
    STAFF_ACCOUNT_NOT_FOUND(1315, "Không tìm thấy tài khoản nhân viên", HttpStatus.NOT_FOUND),
    STAFF_NOT_FOUND(1316, "Không tìm thấy nhân viên", HttpStatus.NOT_FOUND),
    STAFF_ACCOUNT_EXISTED(1317, "Tài khoản đã tồn tại", HttpStatus.BAD_REQUEST),
    STAFF_FIRST_NAME_REQUIRED(1318, "Tên là bắt buộc", HttpStatus.BAD_REQUEST),
    STAFF_FIRST_NAME_LENGTH(1318, "Tên phải từ 2 đến 100 ký tự", HttpStatus.BAD_REQUEST),
    STAFF_LAST_NAME_REQUIRED(1319, "Họ là bắt buộc", HttpStatus.BAD_REQUEST),
    STAFF_LAST_NAME_LENGTH(1320, "Họ phải từ 2 đến 100 ký tự", HttpStatus.BAD_REQUEST),
    STAFF_MIDDLE_NAME_LENGTH(1321, "Tên đệm tối đa 100 ký tự", HttpStatus.BAD_REQUEST),
    STAFF_ROLE_NAMES_EMPTY(1322, "Danh sách vai trò không được để trống", HttpStatus.BAD_REQUEST),

    // ===== DEPARTMENT =====
    DEPARTMENT_NAME_EMPTY(1401, "Tên khoa không được để trống", HttpStatus.BAD_REQUEST),
    DEPARTMENT_NAME_LENGTH(1402, "Tên khoa phải từ 3 đến 100 ký tự", HttpStatus.BAD_REQUEST),
    DEPARTMENT_DESCRIPTION_LENGTH(1403, "Mô tả phải từ 3 đến 500 ký tự", HttpStatus.BAD_REQUEST),
    DEPARTMENT_ROOM_EMPTY(1404, "Số phòng không được để trống", HttpStatus.BAD_REQUEST),
    DEPARTMENT_ROOM_LENGTH(1405, "Số phòng phải từ 2 đến 5 ký tự", HttpStatus.BAD_REQUEST),
    DEPARTMENT_TYPE_EMPTY(1406, "Loại khoa không được để trống", HttpStatus.BAD_REQUEST),
    DEPARTMENT_NOT_FOUND(1407, "Không tìm thấy khoa", HttpStatus.NOT_FOUND),
    DEPARTMENT_ROOM_EXISTED(1408, "Số phòng đã tồn tại", HttpStatus.BAD_REQUEST),
    INVALID_ROOM_FOR_DEPARTMENT(1409,  "Phòng không tồn tại, không đúng chuyên khoa hoặc đã quá tải", HttpStatus.BAD_REQUEST),
    DEPARTMENT_TYPE_NAME_EMPTY(1410, "Tên loại khoa không được để trống", HttpStatus.BAD_REQUEST),
    DEPARTMENT_TYPE_NAME_LENGTH(1411, "Tên loại khoa phải từ 3 đến 100 ký tự", HttpStatus.BAD_REQUEST),
    DEPARTMENT_TYPE_DESCRIPTION_LENGTH(1412, "Mô tả loại khoa phải từ 3 đến 500 ký tự", HttpStatus.BAD_REQUEST),
    DEPARTMENT_TYPE_NAME_EXISTED(1413, "Tên loại khoa đã tồn tại", HttpStatus.BAD_REQUEST),
    DEPARTMENT_TYPE_NOT_FOUND(1414, "Không tìm thấy loại khoa", HttpStatus.NOT_FOUND),
    DEPARTMENT_TYPE_ID_EMPTY(1415, "Mã loại khoa không được để trống", HttpStatus.BAD_REQUEST),

    // ===== SERVICE =====
    SERVICE_NAME_EMPTY(1501, "Tên dịch vụ không được để trống", HttpStatus.BAD_REQUEST),
    SERVICE_NAME_LENGTH(1502, "Tên dịch vụ phải từ 3 đến 100 ký tự", HttpStatus.BAD_REQUEST),
    SERVICE_DESCRIPTION_LENGTH(1503, "Mô tả dịch vụ phải từ 3 đến 500 ký tự", HttpStatus.BAD_REQUEST),
    MEDICAL_SERVICE_NOT_FOUND(1504, "Không tìm thấy dịch vụ", HttpStatus.NOT_FOUND),
    SERVICE_CODE_EXISTED(1505, "Mã dịch vụ đã tồn tại", HttpStatus.BAD_REQUEST),
    PRICE_INVALID_FORMAT(1506, "Giá phải tối đa 12 chữ số trước dấu thập phân và tối đa 3 chữ số sau dấu thập phân", HttpStatus.BAD_REQUEST),
    PRICE_EMPTY(1507, "Giá không được để trống", HttpStatus.BAD_REQUEST),
    PRICE_MIN_0(1508, "Giá phải lớn hơn hoặc bằng 0", HttpStatus.BAD_REQUEST),
    DISCOUNT_MIN_0(1509, "Giảm giá phải lớn hơn hoặc bằng 0", HttpStatus.BAD_REQUEST),
    DISCOUNT_MAX_100(1510, "Giảm giá phải nhỏ hơn hoặc bằng 100", HttpStatus.BAD_REQUEST),
    DISCOUNT_INVALID_FORMAT(1511, "Giảm giá phải nằm trong khoảng 0.00 đến 100.00", HttpStatus.BAD_REQUEST),
    VAT_EMPTY(1512, "VAT không được để trống", HttpStatus.BAD_REQUEST),
    VAT_INVALID_FORMAT(1513, "VAT phải là 0, 8 hoặc 10", HttpStatus.BAD_REQUEST),
    DEPARTMENT_ID_EMPTY(1514, "Mã khoa không được để trống", HttpStatus.BAD_REQUEST),
    MEDICAL_SERVICE_ID_REQUIRED(1515, "Mã dịch vụ khoa không được để trống", HttpStatus.BAD_REQUEST),
    MEDICAL_SERVICE_PRICE_NOT_FOUND(1516, "Không tìm thấy giá dịch vụ khoa", HttpStatus.NOT_FOUND),
    CANNOT_CHANGE_DEPARTMENT_FOR_DEFAULT_SERVICE(1517, "Không thể thay đổi khoa cho dịch vụ mặc định", HttpStatus.BAD_REQUEST),

    // ===== TENANT =====
    TENANT_CODE_EXISTED(3001, "Mã bệnh viện đã tồn tại", HttpStatus.BAD_REQUEST),
    TENANT_NOT_FOUND(3002, "Không tìm thấy bệnh viện", HttpStatus.NOT_FOUND),
    TENANT_NAME_REQUIRED(3003, "Tên bệnh viện là bắt buộc", HttpStatus.BAD_REQUEST),
    TENANT_CODE_REQUIRED(3004, "Mã bệnh viện là bắt buộc", HttpStatus.BAD_REQUEST),
    TENANT_EMAIL_REQUIRED(3005, "Email bệnh viện là bắt buộc", HttpStatus.BAD_REQUEST),
    TENANT_EMAIL_INVALID(3006, "Email bệnh viện không hợp lệ", HttpStatus.BAD_REQUEST),
    TENANT_PHONE_REQUIRED(3007, "Số điện thoại bệnh viện là bắt buộc", HttpStatus.BAD_REQUEST),
    TENANT_PHONE_INVALID(3008, "Số điện thoại bệnh viện không hợp lệ", HttpStatus.BAD_REQUEST),
    TENANT_SERVICE_PACKAGE_REQUIRED(3009, "Gói dịch vụ bệnh viện là bắt buộc", HttpStatus.BAD_REQUEST),
    TENANT_EMAIL_EXISTED(3010, "Email bệnh viện đã tồn tại", HttpStatus.BAD_REQUEST),
    TENANT_PHONE_EXISTED(3011, "Số điện thoại bệnh viện đã tồn tại", HttpStatus.BAD_REQUEST),

    // ===== ROLE & PERMISSION =====
    ROLE_NOT_FOUND(1601, "Không tìm thấy vai trò", HttpStatus.NOT_FOUND),
    PERMISSION_NOT_FOUND(1602, "Không tìm thấy quyền", HttpStatus.NOT_FOUND),
    ROLE_ALREADY_EXISTS(1603, "Vai trò đã tồn tại", HttpStatus.CONFLICT),
    PERMISSION_ALREADY_EXISTS(1604, "Quyền đã tồn tại", HttpStatus.CONFLICT),

    // ===== QUEUE PATIENT =====
    QUEUE_PATIENT_NOT_FOUND(1701, "Không tìm thấy bệnh nhân trong hàng chờ", HttpStatus.NOT_FOUND),
    QUEUE_PATIENT_DUPLICATE_WAITING(1702, "Bệnh nhân đã có trong hàng chờ", HttpStatus.BAD_REQUEST),
    QUEUE_PATIENT_INVALID_STATUS(1703, "Trạng thái hàng chờ không hợp lệ", HttpStatus.BAD_REQUEST),
    QUEUE_PATIENT_ALREADY_CHECKED_OUT(1704, "Bệnh nhân đã được xuất viện", HttpStatus.BAD_REQUEST),
    QUEUE_NOT_FOUND(1705, "Không tìm thấy hàng chờ", HttpStatus.NOT_FOUND),
    QUEUE_PATIENT_ALREADY_FINISHED(1706, "Bệnh nhân đã hoàn thành khám", HttpStatus.BAD_REQUEST),
    QUEUE_ORDER_CONFLICT(1707, "Thứ tự hàng chờ bị xung đột", HttpStatus.BAD_REQUEST),
    ALREADY_IN_QUEUE(1708, "Bệnh nhân đã có trong trạng thái chờ hoặc đang khám", HttpStatus.BAD_REQUEST),
    REGISTERED_TIME_REQUIRED(1709, "Thời gian đăng ký là bắt buộc", HttpStatus.BAD_REQUEST),
    INVALID_QUEUE_DATE(1710, "Ngày hàng chờ không được ở trong quá khứ", HttpStatus.BAD_REQUEST),
    SPECIALIZATION_ID_REQUIRED(1711, "Mã chuyên khoa là bắt buộc", HttpStatus.BAD_REQUEST),
    INVALID_STATUS_TRANSITION(1712, "Không thể cập nhật trạng thái vì bệnh nhân đã hoàn thành khám", HttpStatus.BAD_REQUEST),
    INVALID_QUEUE_ORDER(1713, "Không thể gọi bệnh nhân vì còn người đến trước chưa khám hoặc có người ưu tiên", HttpStatus.BAD_REQUEST),
    ROOMS_OVERLOADED(1714, "Tất cả phòng của chuyên khoa này đã quá tải", HttpStatus.BAD_REQUEST),

    // ===== INVOICE =====
    INVOICE_NOT_FOUND(1801, "Không tìm thấy hóa đơn", HttpStatus.NOT_FOUND),
    INVOICE_STATUS_INVALID(1802, "Trạng thái hóa đơn không hợp lệ", HttpStatus.BAD_REQUEST),
    INVOICE_PATIENT_NOT_FOUND(1803, "Không tìm thấy bệnh nhân của hóa đơn", HttpStatus.NOT_FOUND),
    INVOICE_ALREADY_PAID(1804, "Hóa đơn đã được thanh toán", HttpStatus.BAD_REQUEST),
    INVOICE_ALREADY_CANCELLED(1805, "Hóa đơn đã bị hủy", HttpStatus.BAD_REQUEST),
    INVOICE_ID_EMPTY(1806, "Mã hóa đơn là bắt buộc", HttpStatus.BAD_REQUEST),
    PAYMENT_TYPE_INVALID(1808, "Hình thức thanh toán không hợp lệ", HttpStatus.BAD_REQUEST),
    MEDICAL_RECORD_NOT_FOUND(1809, "Không tìm thấy hồ sơ bệnh án", HttpStatus.NOT_FOUND),
    MULTIPLE_MEDICAL_RECORDS_FOUND(1810, "Tìm thấy nhiều hồ sơ bệnh án", HttpStatus.BAD_REQUEST),
    MEDICAL_ORDER_NOT_FOUND(1811, "Không tìm thấy y lệnh", HttpStatus.NOT_FOUND),
    INVOICE_PDF_CREATION_FAILED(1812, "Tạo file PDF hóa đơn thất bại", HttpStatus.INTERNAL_SERVER_ERROR),
    PAYMENT_REQUIRED(1813, "Cần thanh toán", HttpStatus.BAD_REQUEST),
    VISIT_ID_REQUIRED(1814, "Mã lượt khám là bắt buộc", HttpStatus.BAD_REQUEST),
    SERVICES_REQUIRED(1815, "Dịch vụ là bắt buộc", HttpStatus.BAD_REQUEST),
    TEMPERATURE_TOO_LOW(1816, "Nhiệt độ quá thấp", HttpStatus.BAD_REQUEST),
    TEMPERATURE_TOO_HIGH(1817, "Nhiệt độ quá cao", HttpStatus.BAD_REQUEST),
    RESPIRATORY_RATE_TOO_LOW(1818, "Nhịp thở quá thấp", HttpStatus.BAD_REQUEST),
    RESPIRATORY_RATE_TOO_HIGH(1819, "Nhịp thở quá cao", HttpStatus.BAD_REQUEST),
    INVALID_BLOOD_PRESSURE(1820, "Huyết áp không hợp lệ", HttpStatus.BAD_REQUEST),
    HEART_RATE_TOO_LOW(1821, "Nhịp tim quá thấp", HttpStatus.BAD_REQUEST),
    HEART_RATE_TOO_HIGH(1822, "Nhịp tim quá cao", HttpStatus.BAD_REQUEST),
    HEIGHT_TOO_LOW(1823, "Chiều cao quá thấp", HttpStatus.BAD_REQUEST),
    WEIGHT_TOO_LOW(1824, "Cân nặng quá thấp", HttpStatus.BAD_REQUEST),
    BMI_TOO_LOW(1825, "Chỉ số BMI quá thấp", HttpStatus.BAD_REQUEST),
    BMI_TOO_HIGH(1826, "Chỉ số BMI quá cao", HttpStatus.BAD_REQUEST),
    SPO2_TOO_LOW(1827, "SpO2 quá thấp", HttpStatus.BAD_REQUEST),
    SPO2_TOO_HIGH(1828, "SpO2 quá cao", HttpStatus.BAD_REQUEST),
    NOTES_TOO_LONG(1829, "Ghi chú quá dài", HttpStatus.BAD_REQUEST),
    SUMMARY_REQUIRED(1830, "Tóm tắt là bắt buộc", HttpStatus.BAD_REQUEST),
    INVALID_OPERATION(1831, "Thao tác không hợp lệ", HttpStatus.BAD_REQUEST),

    // ===== FILE =====
    FILE_NOT_PROVIDED(1901, "Chưa cung cấp file", HttpStatus.BAD_REQUEST),
    FILE_UPLOAD_FAILED(1902, "Tải file lên thất bại", HttpStatus.INTERNAL_SERVER_ERROR),
    FILE_DELETE_FAILED(1903, "Xóa file thất bại", HttpStatus.INTERNAL_SERVER_ERROR),

    // ===== MEDICAL RESULT =====
    MEDICAL_RESULT_IS_COMPLETED(2001, "Kết quả khám đã được hoàn tất", HttpStatus.BAD_REQUEST),
    MEDICAL_RESULT_NOT_FOUND(2002, "Không tìm thấy kết quả khám", HttpStatus.NOT_FOUND),

    // ===== FILE TEMPLATE =====
    UPLOAD_TO_VPS_FAILED(2101, "Tải file lên máy chủ thất bại", HttpStatus.INTERNAL_SERVER_ERROR),
    TEMPLATE_FILE_NOT_FOUND(2102, "Không tìm thấy file mẫu", HttpStatus.NOT_FOUND),
    CANNOT_DELETE_DEFAULT_TEMPLATE(2103, "Không thể xóa mẫu mặc định", HttpStatus.BAD_REQUEST),
    CANNOT_REMOVE_LAST_DEFAULT_TEMPLATE(2104, "Không thể xóa mẫu mặc định cuối cùng", HttpStatus.BAD_REQUEST),
    MEDICAL_RECORD_PDF_FAILED(2105, "Tạo PDF hồ sơ bệnh án thất bại", HttpStatus.INTERNAL_SERVER_ERROR),
    ALREADY_HAS_DEFAULT_TEMPLATE(2106, "Đã có mẫu mặc định", HttpStatus.BAD_REQUEST),
    CANNOT_DELETE_LAST_TEMPLATE(2107, "Không thể xóa mẫu cuối cùng", HttpStatus.BAD_REQUEST),
    DEFAULT_TEMPLATE_NOT_FOUND(2108, "Không tìm thấy mẫu mặc định", HttpStatus.NOT_FOUND),

    // ===== WORK SCHEDULE =====
    STAFF_ID_REQUIRED(2201, "Mã nhân viên là bắt buộc", HttpStatus.BAD_REQUEST),
    SHIFTS_REQUIRED(2202, "Ca làm việc là bắt buộc", HttpStatus.BAD_REQUEST),
    DAYS_OF_WEEK_REQUIRED(2203, "Ngày trong tuần là bắt buộc", HttpStatus.BAD_REQUEST),
    START_DATE_REQUIRED(2204, "Ngày bắt đầu là bắt buộc", HttpStatus.BAD_REQUEST),
    END_DATE_REQUIRED(2205, "Ngày kết thúc là bắt buộc", HttpStatus.BAD_REQUEST),
    START_DATE_MUST_BE_NOW_OR_FUTURE(2206, "Ngày bắt đầu phải từ hiện tại trở đi", HttpStatus.BAD_REQUEST),
    END_DATE_MUST_BE_IN_FUTURE(2207, "Ngày kết thúc phải ở tương lai", HttpStatus.BAD_REQUEST),
    NOTE_TOO_LONG(2208, "Ghi chú quá dài", HttpStatus.BAD_REQUEST),
    WORK_SCHEDULE_NOT_FOUND(2209, "Không tìm thấy lịch làm việc", HttpStatus.NOT_FOUND),
    UNAUTHORIZED_ACTION(2210, "Hành động không được phép", HttpStatus.FORBIDDEN),
    WORK_SCHEDULE_ALREADY_CHECKED_IN(2211, "Đã điểm danh cho lịch làm việc này", HttpStatus.BAD_REQUEST),
    CHECKIN_DATE_INVALID(2212, "Ngày điểm danh phải cùng ngày với lịch làm việc", HttpStatus.BAD_REQUEST),
    SHIFT_DATE_REQUIRED(2213, "Ngày ca làm việc là bắt buộc", HttpStatus.BAD_REQUEST),
    CANNOT_UPDATE_PAST_SCHEDULE(2214, "Không thể cập nhật lịch đã qua", HttpStatus.BAD_REQUEST),
    CANNOT_MOVE_SCHEDULE_TO_PAST(2215, "Không thể chuyển lịch làm việc về quá khứ", HttpStatus.BAD_REQUEST),
    CANNOT_UPDATE_ATTENDED_SCHEDULE(2216, "Không thể cập nhật lịch đã điểm danh", HttpStatus.BAD_REQUEST),
    CANNOT_DELETE_ATTENDED_SCHEDULE(2217, "Không thể xóa lịch đã điểm danh", HttpStatus.BAD_REQUEST),
    CANNOT_DELETE_PAST_SCHEDULE(2218, "Không thể xóa lịch đã qua", HttpStatus.BAD_REQUEST),
    CANNOT_DELETE_WORK_SCHEDULE(2219, "Không thể xóa lịch làm việc", HttpStatus.BAD_REQUEST),
    CANNOT_DELETE_WORK_SCHEDULE_WITH_EMAIL_TASK(2220, "Không thể xóa lịch làm việc có nhiệm vụ email", HttpStatus.BAD_REQUEST),
    CANNOT_REQUEST_LEAVE_FOR_PAST_SCHEDULE(2221, "Không thể xin nghỉ cho lịch đã qua", HttpStatus.BAD_REQUEST),
    LEAVE_REQUEST_TOO_CLOSE(2222, "Xin nghỉ phải trước ít nhất 2 ngày", HttpStatus.BAD_REQUEST),
    WORK_ALREADY_ATTENDED_CANNOT_REQUEST_LEAVE(2223, "Đã điểm danh, không thể xin nghỉ", HttpStatus.BAD_REQUEST),
    REASON_REQUIRED(2224, "Lý do là bắt buộc", HttpStatus.BAD_REQUEST),
    DETAILS_REQUIRED(2225, "Chi tiết là bắt buộc", HttpStatus.BAD_REQUEST),
    WORK_SCHEDULE_NOT_FOUND_FOR_LEAVE(2226, "Không tìm thấy lịch làm việc để xin nghỉ", HttpStatus.NOT_FOUND),
    DATE_MUST_BE_TODAY_OR_FUTURE(2227, "Ngày phải từ hôm nay trở đi", HttpStatus.BAD_REQUEST),
    LEAVE_REQUEST_STATUS_REQUIRED(2228, "Trạng thái đơn xin nghỉ là bắt buộc", HttpStatus.BAD_REQUEST),
    LEAVE_REQUEST_ID_REQUIRED(2229, "Mã đơn xin nghỉ là bắt buộc", HttpStatus.BAD_REQUEST),
    LEAVE_REQUEST_NOT_FOUND(2230, "Không tìm thấy đơn xin nghỉ", HttpStatus.NOT_FOUND),
    LEAVE_REQUEST_ALREADY_PROCESSED(2231, "Đơn xin nghỉ đã được xử lý", HttpStatus.BAD_REQUEST),
    INVALID_LEAVE_STATUS(2232, "Trạng thái xin nghỉ không hợp lệ", HttpStatus.BAD_REQUEST),
    LEAVE_REQUEST_CREATE_DATE_INVALID(2233, "Ngày tạo đơn xin nghỉ không hợp lệ", HttpStatus.BAD_REQUEST),
    SCHEDULE_NOT_FOUND_FOR_LEAVE(2234, "Không tìm thấy lịch để xin nghỉ", HttpStatus.NOT_FOUND),
    CANNOT_APPROVE_LEAVE_FOR_ATTENDED_SHIFT(2235, "Không thể duyệt nghỉ cho ca đã điểm danh", HttpStatus.BAD_REQUEST),
    CANNOT_DELETE_PROCESSED_LEAVE_REQUEST(2236, "Không thể xóa đơn xin nghỉ đã xử lý", HttpStatus.BAD_REQUEST),
    CANNOT_UPDATE_PROCESSED_LEAVE_REQUEST(2237, "Không thể cập nhật đơn xin nghỉ đã xử lý", HttpStatus.BAD_REQUEST),
    WORK_SCHEDULE_ALREADY_EXISTS(2238, "Lịch làm việc đã tồn tại", HttpStatus.BAD_REQUEST),
    CANNOT_CREATE_PAST_SCHEDULE(2239, "Không thể tạo lịch làm việc trong quá khứ", HttpStatus.BAD_REQUEST),
    CHECKIN_NOT_ALLOWED(2240, "Không thể điểm danh", HttpStatus.BAD_REQUEST),

    // ===== SETTING =====
    SETTING_NOT_FOUND(2301, "Không tìm thấy thiết lập", HttpStatus.NOT_FOUND),
    HOSPITAL_NAME_REQUIRED(2401, "Tên bệnh viện là bắt buộc", HttpStatus.BAD_REQUEST),
    HOSPITAL_NAME_LENGTH(2402, "Tên bệnh viện phải từ 3 đến 100 ký tự", HttpStatus.BAD_REQUEST),
    HOSPITAL_PHONE_REQUIRED(2403, "Số điện thoại bệnh viện là bắt buộc", HttpStatus.BAD_REQUEST),
    HOSPITAL_PHONE_LENGTH(2404, "Số điện thoại bệnh viện phải từ 3 đến 100 ký tự", HttpStatus.BAD_REQUEST),
    HOSPITAL_EMAIL_REQUIRED(2405, "Email bệnh viện là bắt buộc", HttpStatus.BAD_REQUEST),
    HOSPITAL_EMAIL_INVALID(2406, "Email bệnh viện không hợp lệ", HttpStatus.BAD_REQUEST),
    HOSPITAL_ADDRESS_REQUIRED(2407, "Địa chỉ bệnh viện là bắt buộc", HttpStatus.BAD_REQUEST),
    HOSPITAL_ADDRESS_LENGTH(2408, "Địa chỉ bệnh viện phải từ 3 đến 100 ký tự", HttpStatus.BAD_REQUEST),
    BANK_ACCOUNT_NUMBER_REQUIRED(2409, "Số tài khoản ngân hàng là bắt buộc", HttpStatus.BAD_REQUEST),
    BANK_ACCOUNT_NUMBER_LENGTH(2410, "Số tài khoản ngân hàng phải từ 3 đến 100 ký tự", HttpStatus.BAD_REQUEST),
    BANK_CODE_REQUIRED(2411, "Mã ngân hàng là bắt buộc", HttpStatus.BAD_REQUEST),
    PAGING_SIZE_REQUIRED(2412, "Kích thước phân trang là bắt buộc", HttpStatus.BAD_REQUEST),
    QUEUE_OPEN_TIME_REQUIRED(2413, "Giờ mở hàng chờ là bắt buộc", HttpStatus.BAD_REQUEST),
    QUEUE_CLOSE_TIME_REQUIRED(2414, "Giờ đóng hàng chờ là bắt buộc", HttpStatus.BAD_REQUEST),
    MIN_BOOKING_DAYS_BEFORE_REQUIRED(2415, "Số ngày đặt trước tối thiểu là bắt buộc", HttpStatus.BAD_REQUEST),
    MIN_BOOKING_DAYS_BEFORE_MIN_0(2416, "Số ngày đặt trước tối thiểu phải >= 0", HttpStatus.BAD_REQUEST),
    MIN_BOOKING_DAYS_BEFORE_MAX_30(2417, "Số ngày đặt trước tối đa là 30", HttpStatus.BAD_REQUEST),
    QUEUE_OPEN_TIME_MUST_BE_BEFORE_CLOSE_TIME(2418, "Giờ mở hàng chờ phải trước giờ đóng", HttpStatus.BAD_REQUEST),
    MIN_LEAVE_DAYS_BEFORE_REQUIRED(2419, "Số ngày xin nghỉ tối thiểu là bắt buộc", HttpStatus.BAD_REQUEST),
    MIN_LEAVE_DAYS_BEFORE_MIN_0(2420, "Số ngày xin nghỉ tối thiểu phải >= 0", HttpStatus.BAD_REQUEST),
    MIN_LEAVE_DAYS_BEFORE_MAX_30(2421, "Số ngày xin nghỉ tối đa là 30", HttpStatus.BAD_REQUEST),
    DOC_SHIFT_QUOTA_REQUIRED(2422, "Chỉ tiêu bệnh nhân mỗi bác sĩ/ca là bắt buộc.", HttpStatus.BAD_REQUEST),
    DOC_SHIFT_QUOTA_MIN_0(2423, "Chỉ tiêu bệnh nhân mỗi bác sĩ/ca phải ≥ 0.", HttpStatus.BAD_REQUEST),

    // ===== TRANSACTION HISTORY =====
    TRANSACTION_NOT_FOUND(2501, "Không tìm thấy giao dịch", HttpStatus.NOT_FOUND),
    TRANSACTION_TENANT_ID_REQUIRED(2502, "Mã bệnh viện là bắt buộc", HttpStatus.BAD_REQUEST),
    TRANSACTION_SERVICE_PACKAGE_ID_REQUIRED(2503, "Mã gói dịch vụ là bắt buộc", HttpStatus.BAD_REQUEST),
    TRANSACTION_PRICE_REQUIRED(2504, "Giá là bắt buộc", HttpStatus.BAD_REQUEST),
    TRANSACTION_START_DATE_REQUIRED(2505, "Ngày bắt đầu là bắt buộc", HttpStatus.BAD_REQUEST),
    TRANSACTION_END_DATE_REQUIRED(2506, "Ngày kết thúc là bắt buộc", HttpStatus.BAD_REQUEST),
    TRANSACTION_INVALID_BILLING_TYPE(2507, "Kiểu thanh toán không hợp lệ", HttpStatus.BAD_REQUEST),

    // ===== SHIFT =====
    SHIFT_NAME_REQUIRED(2501, "Tên ca làm việc là bắt buộc", HttpStatus.BAD_REQUEST),
    SHIFT_START_TIME_REQUIRED(2502, "Giờ bắt đầu ca là bắt buộc", HttpStatus.BAD_REQUEST),
    SHIFT_END_TIME_REQUIRED(2503, "Giờ kết thúc ca là bắt buộc", HttpStatus.BAD_REQUEST),
    SHIFT_NAME_EXISTS(2504, "Tên ca làm việc đã tồn tại", HttpStatus.BAD_REQUEST),
    OVERLAPPING_TIME(2505, "Thời gian bị chồng lấn", HttpStatus.BAD_REQUEST),
    SHIFT_NOT_FOUND(2506, "Không tìm thấy ca làm việc", HttpStatus.NOT_FOUND),
    LATEST_CHECK_IN_MINUTES_REQUIRED(2507, "Thời gian điểm danh muộn nhất là bắt buộc", HttpStatus.BAD_REQUEST),
    LATEST_CHECK_IN_MINUTES_MAX_60(2509, "Thời gian điểm danh muộn nhất phải dưới 60 phút", HttpStatus.BAD_REQUEST),
    DUPLICATE_SHIFT_IDS(2510, "Trùng mã ca làm việc", HttpStatus.BAD_REQUEST),
    NEW_SCHEDULES_REQUIRED(2511, "Danh sách lịch làm việc mới là bắt buộc", HttpStatus.BAD_REQUEST),
    SHIFT_ID_REQUIRED(2512, "Mã ca làm việc là bắt buộc", HttpStatus.BAD_REQUEST),
    FROM_DATETIME_REQUIRED(2513, "Thời gian bắt đầu là bắt buộc", HttpStatus.BAD_REQUEST),
    TO_DATETIME_REQUIRED(2514, "Thời gian kết thúc là bắt buộc", HttpStatus.BAD_REQUEST),
    INVALID_TIME_RANGE(2515, "Khoảng thời gian không hợp lệ", HttpStatus.BAD_REQUEST),
    NO_WORK_SCHEDULE_IN_RANGE(2516, "Không có lịch làm việc trong khoảng thời gian", HttpStatus.BAD_REQUEST),
    CHECKIN_TIME_INVALID(2517, "Thời gian điểm danh không hợp lệ", HttpStatus.BAD_REQUEST),


    // ===== SPECIALIZATION =====
    SPECIALIZATION_NAME_REQUIRED(2601, "Tên chuyên khoa là bắt buộc", HttpStatus.BAD_REQUEST),
    SPECIALIZATION_NAME_EXISTS(2602, "Tên chuyên khoa đã tồn tại", HttpStatus.BAD_REQUEST),
    SPECIALIZATION_NOT_FOUND(2603, "Không tìm thấy chuyên khoa", HttpStatus.NOT_FOUND),
    SPECIALIZATION_ID_EMPTY(2604, "Mã chuyên khoa không được để trống", HttpStatus.BAD_REQUEST),
    DEPARTMENT_SPECIALIZATION_REQUIRED(2605, "Chuyên khoa là bắt buộc đối với khoa khám", HttpStatus.BAD_REQUEST),

    // ===== REGISTERED ONLINE =====
    REGISTERED_ONLINE_NOT_FOUND(2701, "Không tìm thấy bản đăng ký", HttpStatus.NOT_FOUND),
    REGISTERED_FULL_NAME_REQUIRED(2702, "Họ và tên là bắt buộc", HttpStatus.BAD_REQUEST),
    REGISTERED_EMAIL_REQUIRED(2703, "Email là bắt buộc", HttpStatus.BAD_REQUEST),
    REGISTERED_PHONE_REQUIRED(2704, "Số điện thoại là bắt buộc", HttpStatus.BAD_REQUEST),
    REGISTERED_EMAIL_INVALID(2706, "Email không hợp lệ", HttpStatus.BAD_REQUEST),
    REGISTERED_PHONE_INVALID(2707, "Số điện thoại không hợp lệ", HttpStatus.BAD_REQUEST),
    REGISTERED_FIRST_NAME_REQUIRED(2708, "Tên là bắt buộc", HttpStatus.BAD_REQUEST),
    REGISTERED_LAST_NAME_REQUIRED(2709, "Họ là bắt buộc", HttpStatus.BAD_REQUEST),
    REGISTERED_REGISTERED_AT_REQUIRED(2710, "Thời gian đăng ký là bắt buộc", HttpStatus.BAD_REQUEST),
    REGISTERED_STATUS_INVALID(2711, "Trạng thái không hợp lệ", HttpStatus.BAD_REQUEST),
    REGISTERED_GENDER_INVALID(2712, "Giá trị giới tính không hợp lệ", HttpStatus.BAD_REQUEST),
    REGISTERED_DOB_INVALID(2713, "Ngày sinh không hợp lệ", HttpStatus.BAD_REQUEST),
    REGISTERED_ALREADY_ACTIVE(2714, "Bạn đã đăng ký dịch vụ khám online bằng email hoặc số điện thoại này rồi. Vui lòng kiểm tra lại email để xem thông báo.", HttpStatus.BAD_REQUEST),
    REGISTERED_DATE_TOO_SOON(2715, "Ngày đăng ký phải cách ít nhất 2 ngày từ hôm nay", HttpStatus.BAD_REQUEST),
    REGISTERED_DOB_REQUIRED(2716, "Ngày sinh là bắt buộc", HttpStatus.BAD_REQUEST),
    REGISTERED_GENDER_REQUIRED(2717, "Giới tính là bắt buộc", HttpStatus.BAD_REQUEST),
    REGISTERED_SERVICE_PRICE_MIN_REQUIRED(2718, "Giá dịch vụ tối thiểu là bắt buộc", HttpStatus.BAD_REQUEST),
    DEFAULT_SERVICE_PRICE_INVALID_FORMAT(2719, "Định dạng giá dịch vụ mặc định không hợp lệ", HttpStatus.BAD_REQUEST),
    DEFAULT_SERVICE_PRICE_REQUIRED(2720, "Giá dịch vụ mặc định là bắt buộc", HttpStatus.BAD_REQUEST),
    CANNOT_DELETE_DEFAULT_SERVICE(2721, "Không thể xóa dịch vụ mặc định", HttpStatus.BAD_REQUEST),
    MONTHLY_TARGET_REVENUE_REQUIRED(2722, "Doanh thu mục tiêu hàng tháng là bắt buộc", HttpStatus.BAD_REQUEST),
    MONTHLY_TARGET_REVENUE_MUST_BE_POSITIVE(2723, "Doanh thu mục tiêu hàng tháng phải là số dương", HttpStatus.BAD_REQUEST),

    USER_ID_REQUIRED(2724, "Mã người dùng là bắt buộc", HttpStatus.BAD_REQUEST),
    QUESTION_REQUIRED(2725, "Câu hỏi là bắt buộc", HttpStatus.BAD_REQUEST),

    // ===== ROOM TRANSFER REQUEST =====
    FROM_ROOM_NUMBER_EMPTY(2726, "Phòng chuyển đi không được để trống", HttpStatus.BAD_REQUEST),
    TO_ROOM_NUMBER_EMPTY(2727, "Phòng chuyển đến không được để trống", HttpStatus.BAD_REQUEST),
    TRANSFERRED_BY_ID_EMPTY(2728, "Người thực hiện chuyển phòng không được để trống", HttpStatus.BAD_REQUEST),
    REASON_TOO_LONG(2729, "Lý do chuyển phòng quá dài", HttpStatus.BAD_REQUEST),
    SAME_ROOM(2730, "Phòng chuyển đến phải khác phòng hiện tại", HttpStatus.BAD_REQUEST),
    SERVICE_PACKAGE_NOT_FOUND(2301, "Không tìm thấy gói dịch vụ", HttpStatus.NOT_FOUND),
    DUPLICATE_SERVICE_PACKAGE_NAME(2305, "Tên gói dịch vụ đã tồn tại cho bệnh viện này", HttpStatus.CONFLICT),
    ROOM_TRANSFER_NOT_FOUND(2732, "Phòng không tìm thấy", HttpStatus.NOT_FOUND),
    // ===== FEEDBACK =====
    FEEDBACK_NOT_FOUND(2731, "Không tìm thấy phản hồi", HttpStatus.NOT_FOUND),

    METRIC_ALERT_NOT_FOUND(2733, "Không tìm thấy thống báo", HttpStatus.NOT_FOUND),

    ;

    private int code;
    private String message;
    private HttpStatusCode statusCode;
}
